/** Tech Center research tree catalog (structure from community calculators). */
window.LW_RESEARCH_CATALOG = [
  {
    id: "development",
    slug: "development",
    name: "Development",
    description: "Builder speed, infirmary, barracks, and research speed.",
    group: "core",
  },
  {
    id: "economy",
    slug: "economy",
    name: "Economy",
    description: "Resource output, gathering, and protection.",
    group: "core",
  },
  {
    id: "hero",
    slug: "hero",
    name: "Hero",
    description: "Hero EXP, skill medals, and recruitment bonuses.",
    group: "core",
  },
  {
    id: "intercity-truck",
    slug: "intercity-truck",
    name: "Intercity Truck",
    description: "Truck rewards, dispatch speed, and capacity.",
    group: "core",
  },
  {
    id: "the-age-of-oil",
    slug: "the-age-of-oil",
    name: "The Age of Oil",
    description: "Oil-season economy and related Tech Center nodes.",
    group: "core",
  },
  {
    id: "squad-1",
    slug: "squad-1",
    name: "Squad 1",
    description: "Squad 1 combat and capacity research.",
    group: "squad",
  },
  {
    id: "squad-2",
    slug: "squad-2",
    name: "Squad 2",
    description: "Squad 2 combat and capacity research.",
    group: "squad",
  },
  {
    id: "squad-3",
    slug: "squad-3",
    name: "Squad 3",
    description: "Squad 3 combat and capacity research.",
    group: "squad",
  },
  {
    id: "squad-4",
    slug: "squad-4",
    name: "Squad 4",
    description: "Squad 4 combat and capacity research.",
    group: "squad",
  },
  {
    id: "alliance-duel",
    slug: "alliance-duel",
    name: "Alliance Duel",
    description: "Versus / Alliance Duel point and combat bonuses.",
    group: "combat",
  },
  {
    id: "siege-to-seize",
    slug: "siege-to-seize",
    name: "Siege to Seize",
    description: "Siege damage, march, and assault research.",
    group: "combat",
  },
  {
    id: "defense-fortifications",
    slug: "defense-fortifications",
    name: "Defense Fortifications",
    description: "Base defense, wall, and fortification research.",
    group: "combat",
  },
  {
    id: "special-forces",
    slug: "special-forces",
    name: "Special Forces",
    description: "Unit X path — unlock and upgrade T10 troops.",
    group: "combat",
  },
  {
    id: "units",
    slug: "units",
    name: "Units",
    description: "Shared troop training and combat foundations.",
    group: "mastery",
  },
  {
    id: "tank-mastery",
    slug: "tank-mastery",
    name: "Tank Mastery",
    description: "Tank-type damage, HP, and training mastery.",
    group: "mastery",
  },
  {
    id: "missile-mastery",
    slug: "missile-mastery",
    name: "Missile Mastery",
    description: "Missile-type damage, HP, and training mastery.",
    group: "mastery",
  },
  {
    id: "aircraft-mastery",
    slug: "aircraft-mastery",
    name: "Aircraft Mastery",
    description: "Aircraft-type damage, HP, and training mastery.",
    group: "mastery",
  },
  {
    id: "tactical-weapon",
    slug: "tactical-weapon",
    name: "Tactical Weapon",
    description: "Tactical weapon unlocks and upgrade research.",
    group: "mastery",
  },
];
